0 0 dataAuditErrors
2134 0 NWELL_should_be_contacted
2135 0 minority_NWELL_connectors
2136 0 NWELL_soft_connect
2141 0 PTUB_should_be_contacted
2142 0 minority_PTUB_connectors
2143 0 PTUB_soft_connect
2148 0 NDF_should_be_contacted
2149 0 minority_NDF_connectors
2150 0 NDF_soft_connect
2155 0 NBASE_should_be_contacted
2156 0 minority_NBASE_connectors
2157 0 NBASE_soft_connect
2162 0 PDF_should_be_contacted
2163 0 minority_PDF_connectors
2164 0 PDF_soft_connect
2169 0 tiedtub_nbuf_StampErrorFloat
2170 0 tiedtub_nbuf_StampErrorConnect
2171 0 tiedtub_nbuf_StampErrorMult
2186 0 handle_wafer_must_have_same_net
2193 0 handle_wafer_contact_is_necessary
2196 0 PWELL4_should_be_contacted
2197 0 minority_PWELL4_connectors
2198 0 PWELL4_soft_connect
2287 0 HWNTUBs_of_Handle_wafer_diodes_must_have_same_net
6982 0 malformed device nem
6983 0 malformed device ndm
6984 0 malformed device pem
6985 0 malformed device pem_5
6986 0 malformed device nnm
6987 0 malformed device pemti
6988 0 malformed device nmva
6989 0 malformed device pmva
6990 0 malformed device phsj1_7
6991 0 malformed device phsj1_10
6992 0 malformed device phsj1_16c
6993 0 malformed device nhvta
6994 0 malformed device nhvtb
6995 0 malformed device nhvu
6996 0 malformed device ndhvt
6997 0 malformed device ndhvta
6998 0 malformed device phvta
6999 0 malformed device phvtb
7000 0 malformed device phvu
7001 0 malformed device nhsj1_7
7002 0 malformed device nhsj1_10
7003 0 malformed device nhsj1_16c
7004 0 malformed device nisj1_16
7005 0 malformed device ne
7006 0 malformed device nel
7007 0 malformed device pe
7008 0 malformed device pel
7009 0 malformed device pe_5
7010 0 malformed device pel_5
7011 0 malformed device nn
7012 0 malformed device peti
7013 0 malformed device mosvc
7014 0 malformed device mosvci
7015 0 malformed device mosvcm
7016 0 malformed device mosvcim
7017 0 malformed device d_csf2p
7018 0 malformed device d_csf3p
7019 0 malformed device d_csf3
7020 0 malformed device d_csf3a
7021 0 malformed device d_csf4
7022 0 malformed device d_csf4a
7023 0 malformed device d_csft5
7024 0 malformed device d_csft5a
7025 0 malformed device d_capsw4
7026 0 malformed device d_capsw3
7027 0 malformed device cmm23f
7028 0 malformed device cmm34f
7029 0 malformed device cmm
7030 0 malformed device cmmh23f
7031 0 malformed device cmmh34f
7032 0 malformed device cmmh
7033 0 malformed device cdmm
7034 0 malformed device cdmmh
7035 0 malformed device cdmma
7036 0 malformed device cdmmha
7037 0 malformed device ctmm
7038 0 malformed device ctmmh
7039 0 malformed device rnw
7040 0 malformed device rnw_scr
7041 0 malformed device rnwm
7042 0 malformed device rnwm_scr
7043 0 malformed device rxw2ti
7044 0 malformed device rnp1h_1
7045 0 malformed device rnp1h_3_pw
7046 0 malformed device rnp1h_3_nw
7047 0 malformed device rpp1k1_1
7048 0 malformed device rpp1k1_3_pw
7049 0 malformed device rpp1k1_3_nw
7050 0 malformed device rpp1k1a_1
7051 0 malformed device rpp1k1a_3_pw
7052 0 malformed device rpp1k1a_3_nw
7053 0 malformed device rnp1_1
7054 0 malformed device rnp1_3_pw
7055 0 malformed device rnp1_3_nw
7056 0 malformed device rpp1_1
7057 0 malformed device rpp1_3_pw
7058 0 malformed device rpp1_3_nw
7059 0 malformed device rpp1s_1
7060 0 malformed device rpp1s_3_pw
7061 0 malformed device rpp1s_3_nw
7062 0 malformed device rdn
7063 0 malformed device rdn_g
7064 0 malformed device rdp
7065 0 malformed device rdp_g
7066 0 malformed device rdnm
7067 0 malformed device rdnm_g
7068 0 malformed device rdnm_pw4
7069 0 malformed device rdnm_dpc
7070 0 malformed device rdpm
7071 0 malformed device rdpm_g
7072 0 malformed device met1res
7073 0 malformed device met2res
7074 0 malformed device met3res
7075 0 malformed device mtpres
7076 0 malformed device met4res
7077 0 malformed device mtplres
8111 0 unstable device for mtl_vm25_Device_212
8112 0 unpreserved device mtl_vm25_Device_212
8113 0 unstable device for mtl_vm60_Device_211
8114 0 unpreserved device mtl_vm60_Device_211
8115 0 unstable device for mtl_vm100_Device_210
8116 0 unpreserved device mtl_vm100_Device_210
8117 0 unstable device for mtl_vm200_Device_209
8118 0 unpreserved device mtl_vm200_Device_209
8119 0 unstable device for mtl_v25_Device_208
8120 0 unpreserved device mtl_v25_Device_208
8121 0 unstable device for mtl_v60_Device_207
8122 0 unpreserved device mtl_v60_Device_207
8123 0 unstable device for mtl_v100_Device_206
8124 0 unpreserved device mtl_v100_Device_206
8125 0 unstable device for mtl_v200_Device_205
8126 0 unpreserved device mtl_v200_Device_205
8127 0 unstable device for mt_vm25_Device_204
8128 0 unpreserved device mt_vm25_Device_204
8129 0 unstable device for mt_vm60_Device_203
8130 0 unpreserved device mt_vm60_Device_203
8131 0 unstable device for mt_vm100_Device_202
8132 0 unpreserved device mt_vm100_Device_202
8133 0 unstable device for mt_vm200_Device_201
8134 0 unpreserved device mt_vm200_Device_201
8135 0 unstable device for mt_v25_Device_200
8136 0 unpreserved device mt_v25_Device_200
8137 0 unstable device for mt_v60_Device_199
8138 0 unpreserved device mt_v60_Device_199
8139 0 unstable device for mt_v100_Device_198
8140 0 unpreserved device mt_v100_Device_198
8141 0 unstable device for mt_v200_Device_197
8142 0 unpreserved device mt_v200_Device_197
8143 0 unstable device for m4_vm25_Device_196
8144 0 unpreserved device m4_vm25_Device_196
8145 0 unstable device for m4_vm60_Device_195
8146 0 unpreserved device m4_vm60_Device_195
8147 0 unstable device for m4_vm100_Device_194
8148 0 unpreserved device m4_vm100_Device_194
8149 0 unstable device for m4_vm200_Device_193
8150 0 unpreserved device m4_vm200_Device_193
8151 0 unstable device for m4_v25_Device_192
8152 0 unpreserved device m4_v25_Device_192
8153 0 unstable device for m4_v60_Device_191
8154 0 unpreserved device m4_v60_Device_191
8155 0 unstable device for m4_v100_Device_190
8156 0 unpreserved device m4_v100_Device_190
8157 0 unstable device for m4_v200_Device_189
8158 0 unpreserved device m4_v200_Device_189
8159 0 unstable device for m3_vm25_Device_188
8160 0 unpreserved device m3_vm25_Device_188
8161 0 unstable device for m3_vm60_Device_187
8162 0 unpreserved device m3_vm60_Device_187
8163 0 unstable device for m3_vm100_Device_186
8164 0 unpreserved device m3_vm100_Device_186
8165 0 unstable device for m3_vm200_Device_185
8166 0 unpreserved device m3_vm200_Device_185
8167 0 unstable device for m3_v25_Device_184
8168 0 unpreserved device m3_v25_Device_184
8169 0 unstable device for m3_v60_Device_183
8170 0 unpreserved device m3_v60_Device_183
8171 0 unstable device for m3_v100_Device_182
8172 0 unpreserved device m3_v100_Device_182
8173 0 unstable device for m3_v200_Device_181
8174 0 unpreserved device m3_v200_Device_181
8175 0 unstable device for m2_vm25_Device_180
8176 0 unpreserved device m2_vm25_Device_180
8177 0 unstable device for m2_vm60_Device_179
8178 0 unpreserved device m2_vm60_Device_179
8179 0 unstable device for m2_vm100_Device_178
8180 0 unpreserved device m2_vm100_Device_178
8181 0 unstable device for m2_vm200_Device_177
8182 0 unpreserved device m2_vm200_Device_177
8183 0 unstable device for m2_v25_Device_176
8184 0 unpreserved device m2_v25_Device_176
8185 0 unstable device for m2_v60_Device_175
8186 0 unpreserved device m2_v60_Device_175
8187 0 unstable device for m2_v100_Device_174
8188 0 unpreserved device m2_v100_Device_174
8189 0 unstable device for m2_v200_Device_173
8190 0 unpreserved device m2_v200_Device_173
8191 0 unstable device for m1_vm25_Device_172
8192 0 unpreserved device m1_vm25_Device_172
8193 0 unstable device for m1_vm60_Device_171
8194 0 unpreserved device m1_vm60_Device_171
8195 0 unstable device for m1_vm100_Device_170
8196 0 unpreserved device m1_vm100_Device_170
8197 0 unstable device for m1_vm200_Device_169
8198 0 unpreserved device m1_vm200_Device_169
8199 0 unstable device for m1_v25_Device_168
8200 0 unpreserved device m1_v25_Device_168
8201 0 unstable device for m1_v60_Device_167
8202 0 unpreserved device m1_v60_Device_167
8203 0 unstable device for m1_v100_Device_166
8204 0 unpreserved device m1_v100_Device_166
8205 0 unstable device for m1_v200_Device_165
8206 0 unpreserved device m1_v200_Device_165
8207 0 unstable device for p1_vm25_Device_164
8208 0 unpreserved device p1_vm25_Device_164
8209 0 unstable device for p1_vm60_Device_163
8210 0 unpreserved device p1_vm60_Device_163
8211 0 unstable device for p1_vm100_Device_162
8212 0 unpreserved device p1_vm100_Device_162
8213 0 unstable device for p1_vm200_Device_161
8214 0 unpreserved device p1_vm200_Device_161
8215 0 unstable device for p1_v25_Device_160
8216 0 unpreserved device p1_v25_Device_160
8217 0 unstable device for p1_v60_Device_159
8218 0 unpreserved device p1_v60_Device_159
8219 0 unstable device for p1_v100_Device_158
8220 0 unpreserved device p1_v100_Device_158
8221 0 unstable device for p1_v200_Device_157
8222 0 unpreserved device p1_v200_Device_157
8223 0 unstable device for p_dnwmmva_DIODE_156
8224 0 unpreserved device p_dnwmmva_DIODE_156
8225 0 unstable device for p_dnnm_DIODE_153
8226 0 unpreserved device p_dnnm_DIODE_153
8227 0 unstable device for p_dnm_DIODE_152
8228 0 unpreserved device p_dnm_DIODE_152
8229 0 unstable device for p_dpm_DIODE_151
8230 0 unpreserved device p_dpm_DIODE_151
8231 0 unstable device for p_dpm_DIODE_155
8232 0 unpreserved device p_dpm_DIODE_155
8233 0 unstable device for p_dnwm_DIODE_150
8234 0 unpreserved device p_dnwm_DIODE_150
8235 0 unstable device for p_dnwm_DIODE_154
8236 0 unpreserved device p_dnwm_DIODE_154
8237 0 unstable device for p_dnn_DIODE_147
8238 0 unpreserved device p_dnn_DIODE_147
8239 0 unstable device for p_dn_DIODE_146
8240 0 unpreserved device p_dn_DIODE_146
8241 0 unstable device for p_dp_DIODE_145
8242 0 unpreserved device p_dp_DIODE_145
8243 0 unstable device for p_dp_DIODE_149
8244 0 unpreserved device p_dp_DIODE_149
8245 0 unstable device for p_dnw_DIODE_144
8246 0 unpreserved device p_dnw_DIODE_144
8247 0 unstable device for p_dnw_DIODE_148
8248 0 unpreserved device p_dnw_DIODE_148
8249 0 unstable device for dfwdnu_DIODE_143
8250 0 unpreserved device dfwdnu_DIODE_143
8251 0 unstable device for dfwdnt_DIODE_142
8252 0 unpreserved device dfwdnt_DIODE_142
8253 0 unstable device for dzb_DIODE_141
8254 0 unpreserved device dzb_DIODE_141
8255 0 unstable device for dfwdn5_DIODE_140
8256 0 unpreserved device dfwdn5_DIODE_140
8257 0 unstable device for dzati_DIODE_139
8258 0 unpreserved device dzati_DIODE_139
8259 0 unstable device for dza_DIODE_138
8260 0 unpreserved device dza_DIODE_138
8261 0 unstable device for dnpati_DIODE_137
8262 0 unpreserved device dnpati_DIODE_137
8263 0 unstable device for dnpa_DIODE_136
8264 0 unpreserved device dnpa_DIODE_136
8265 0 unstable device for ds5a_DIODE_135
8266 0 unpreserved device ds5a_DIODE_135
8267 0 unstable device for dnp7_DIODE_134
8268 0 unpreserved device dnp7_DIODE_134
8269 0 unstable device for dpp7_DIODE_133
8270 0 unpreserved device dpp7_DIODE_133
8271 0 unstable device for dpp6_DIODE_132
8272 0 unpreserved device dpp6_DIODE_132
8273 0 unstable device for dhw3_dev_DIODE_131
8274 0 unpreserved device dhw3_dev_DIODE_131
8275 0 unstable device for dhw2_dev_DIODE_130
8276 0 unpreserved device dhw2_dev_DIODE_130
8277 0 unstable device for dhw2a_dev_DIODE_129
8278 0 unpreserved device dhw2a_dev_DIODE_129
8279 0 unstable device for dfwnsj1_16c_DIODE_128
8280 0 unpreserved device dfwnsj1_16c_DIODE_128
8281 0 unstable device for dfwnsj1_10_DIODE_127
8282 0 unpreserved device dfwnsj1_10_DIODE_127
8283 0 unstable device for dfwnsj1_7_DIODE_126
8284 0 unpreserved device dfwnsj1_7_DIODE_126
8285 0 unstable device for dfwdp2f_DIODE_125
8286 0 unpreserved device dfwdp2f_DIODE_125
8287 0 unstable device for dfwdp1f_DIODE_124
8288 0 unpreserved device dfwdp1f_DIODE_124
8289 0 unstable device for d_dnwm_DIODE_121
8290 0 unpreserved device d_dnwm_DIODE_121
8291 0 unstable device for d_dnwm_DIODE_123
8292 0 unpreserved device d_dnwm_DIODE_123
8293 0 unstable device for d_dnnm_DIODE_120
8294 0 unpreserved device d_dnnm_DIODE_120
8295 0 unstable device for d_dnm_DIODE_119
8296 0 unpreserved device d_dnm_DIODE_119
8297 0 unstable device for d_dpm_DIODE_118
8298 0 unpreserved device d_dpm_DIODE_118
8299 0 unstable device for d_dpm_DIODE_122
8300 0 unpreserved device d_dpm_DIODE_122
8301 0 unstable device for d_dnw_DIODE_115
8302 0 unpreserved device d_dnw_DIODE_115
8303 0 unstable device for d_dnw_DIODE_117
8304 0 unpreserved device d_dnw_DIODE_117
8305 0 unstable device for d_dnn_DIODE_114
8306 0 unpreserved device d_dnn_DIODE_114
8307 0 unstable device for d_dn_DIODE_113
8308 0 unpreserved device d_dn_DIODE_113
8309 0 unstable device for d_dp_DIODE_112
8310 0 unpreserved device d_dp_DIODE_112
8311 0 unstable device for d_dp_DIODE_116
8312 0 unpreserved device d_dp_DIODE_116
8313 0 unstable device for qpv5_BJT_111
8314 0 unpreserved device qpv5_BJT_111
8315 0 unstable device for qnv5_BJT_110
8316 0 unpreserved device qnv5_BJT_110
8317 0 unstable device for qpvme_BJT_109
8318 0 unpreserved device qpvme_BJT_109
8319 0 unstable device for qpvmf_BJT_108
8320 0 unpreserved device qpvmf_BJT_108
8321 0 unstable device for qpvmg_BJT_107
8322 0 unpreserved device qpvmg_BJT_107
8323 0 unstable device for qpvma_BJT_106
8324 0 unpreserved device qpvma_BJT_106
8325 0 unstable device for qpvmb_BJT_105
8326 0 unpreserved device qpvmb_BJT_105
8327 0 unstable device for qpvmc_BJT_104
8328 0 unpreserved device qpvmc_BJT_104
8329 0 unstable device for qpve_BJT_103
8330 0 unpreserved device qpve_BJT_103
8331 0 unstable device for qpvf_BJT_102
8332 0 unpreserved device qpvf_BJT_102
8333 0 unstable device for qpvg_BJT_101
8334 0 unpreserved device qpvg_BJT_101
8335 0 unstable device for qpva_BJT_100
8336 0 unpreserved device qpva_BJT_100
8337 0 unstable device for qpvb_BJT_99
8338 0 unpreserved device qpvb_BJT_99
8339 0 unstable device for qpvc_BJT_98
8340 0 unpreserved device qpvc_BJT_98
8341 0 unstable device for pfuse_RES_97
8342 0 unpreserved device pfuse_RES_97
8343 0 unstable device for mtplres_RES_96
8344 0 unpreserved device mtplres_RES_96
8345 0 unstable device for met4res_RES_95
8346 0 unpreserved device met4res_RES_95
8347 0 unstable device for mtpres_RES_94
8348 0 unpreserved device mtpres_RES_94
8349 0 unstable device for met3res_RES_93
8350 0 unpreserved device met3res_RES_93
8351 0 unstable device for met2res_RES_92
8352 0 unpreserved device met2res_RES_92
8353 0 unstable device for met1res_RES_91
8354 0 unpreserved device met1res_RES_91
8355 0 unstable device for rdpm_g_RES_90
8356 0 unpreserved device rdpm_g_RES_90
8357 0 unstable device for rdpm_RES_89
8358 0 unpreserved device rdpm_RES_89
8359 0 unstable device for rdnm_dpc_RES_88
8360 0 unpreserved device rdnm_dpc_RES_88
8361 0 unstable device for rdnm_pw4_RES_87
8362 0 unpreserved device rdnm_pw4_RES_87
8363 0 unstable device for rdnm_g_RES_86
8364 0 unpreserved device rdnm_g_RES_86
8365 0 unstable device for rdnm_RES_85
8366 0 unpreserved device rdnm_RES_85
8367 0 unstable device for rdp_g_RES_84
8368 0 unpreserved device rdp_g_RES_84
8369 0 unstable device for rdp_RES_83
8370 0 unpreserved device rdp_RES_83
8371 0 unstable device for rdn_g_RES_82
8372 0 unpreserved device rdn_g_RES_82
8373 0 unstable device for rdn_RES_81
8374 0 unpreserved device rdn_RES_81
8375 0 unstable device for rpp1s_3_nw_RES_80
8376 0 unpreserved device rpp1s_3_nw_RES_80
8377 0 unstable device for rpp1s_3_pw_RES_79
8378 0 unpreserved device rpp1s_3_pw_RES_79
8379 0 unstable device for rpp1s_1_RES_78
8380 0 unpreserved device rpp1s_1_RES_78
8381 0 unstable device for rpp1_3_nw_RES_77
8382 0 unpreserved device rpp1_3_nw_RES_77
8383 0 unstable device for rpp1_3_pw_RES_76
8384 0 unpreserved device rpp1_3_pw_RES_76
8385 0 unstable device for rpp1_1_RES_75
8386 0 unpreserved device rpp1_1_RES_75
8387 0 unstable device for rnp1_3_nw_RES_74
8388 0 unpreserved device rnp1_3_nw_RES_74
8389 0 unstable device for rnp1_3_pw_RES_73
8390 0 unpreserved device rnp1_3_pw_RES_73
8391 0 unstable device for rnp1_1_RES_72
8392 0 unpreserved device rnp1_1_RES_72
8393 0 unstable device for rpp1k1a_3_nw_RES_71
8394 0 unpreserved device rpp1k1a_3_nw_RES_71
8395 0 unstable device for rpp1k1a_3_pw_RES_70
8396 0 unpreserved device rpp1k1a_3_pw_RES_70
8397 0 unstable device for rpp1k1a_1_RES_69
8398 0 unpreserved device rpp1k1a_1_RES_69
8399 0 unstable device for rpp1k1_3_nw_RES_68
8400 0 unpreserved device rpp1k1_3_nw_RES_68
8401 0 unstable device for rpp1k1_3_pw_RES_67
8402 0 unpreserved device rpp1k1_3_pw_RES_67
8403 0 unstable device for rpp1k1_1_RES_66
8404 0 unpreserved device rpp1k1_1_RES_66
8405 0 unstable device for rnp1h_3_nw_RES_65
8406 0 unpreserved device rnp1h_3_nw_RES_65
8407 0 unstable device for rnp1h_3_pw_RES_64
8408 0 unpreserved device rnp1h_3_pw_RES_64
8409 0 unstable device for rnp1h_1_RES_63
8410 0 unpreserved device rnp1h_1_RES_63
8411 0 unstable device for rxw2ti_RES_62
8412 0 unpreserved device rxw2ti_RES_62
8413 0 unstable device for rnwm_scr_RES_61
8414 0 unpreserved device rnwm_scr_RES_61
8415 0 unstable device for rnwm_RES_60
8416 0 unpreserved device rnwm_RES_60
8417 0 unstable device for rnw_scr_RES_59
8418 0 unpreserved device rnw_scr_RES_59
8419 0 unstable device for rnw_RES_58
8420 0 unpreserved device rnw_RES_58
8421 0 unstable device for ctmmh_CAP_57
8422 0 unpreserved device ctmmh_CAP_57
8423 0 unstable device for ctmm_CAP_56
8424 0 unpreserved device ctmm_CAP_56
8425 0 unstable device for cdmmha_CAP_55
8426 0 unpreserved device cdmmha_CAP_55
8427 0 unstable device for cdmma_CAP_54
8428 0 unpreserved device cdmma_CAP_54
8429 0 unstable device for cdmmh_CAP_53
8430 0 unpreserved device cdmmh_CAP_53
8431 0 unstable device for cdmm_CAP_52
8432 0 unpreserved device cdmm_CAP_52
8433 0 unstable device for cmmh_CAP_51
8434 0 unpreserved device cmmh_CAP_51
8435 0 unstable device for cmmh34f_CAP_50
8436 0 unpreserved device cmmh34f_CAP_50
8437 0 unstable device for cmmh23f_CAP_49
8438 0 unpreserved device cmmh23f_CAP_49
8439 0 unstable device for cmm_CAP_48
8440 0 unpreserved device cmm_CAP_48
8441 0 unstable device for cmm34f_CAP_47
8442 0 unpreserved device cmm34f_CAP_47
8443 0 unstable device for cmm23f_CAP_46
8444 0 unpreserved device cmm23f_CAP_46
8445 0 unstable device for d_capsw3_CAP_45
8446 0 unpreserved device d_capsw3_CAP_45
8447 0 unstable device for d_capsw4_CAP_44
8448 0 unpreserved device d_capsw4_CAP_44
8449 0 unstable device for d_csft5a_CAP_43
8450 0 unpreserved device d_csft5a_CAP_43
8451 0 unstable device for d_csft5_CAP_42
8452 0 unpreserved device d_csft5_CAP_42
8453 0 unstable device for d_csf4a_CAP_41
8454 0 unpreserved device d_csf4a_CAP_41
8455 0 unstable device for d_csf4_CAP_40
8456 0 unpreserved device d_csf4_CAP_40
8457 0 unstable device for d_csf3a_CAP_39
8458 0 unpreserved device d_csf3a_CAP_39
8459 0 unstable device for d_csf3_CAP_38
8460 0 unpreserved device d_csf3_CAP_38
8461 0 unstable device for d_csf3p_CAP_37
8462 0 unpreserved device d_csf3p_CAP_37
8463 0 unstable device for d_csf2p_CAP_36
8464 0 unpreserved device d_csf2p_CAP_36
8465 0 unstable device for mosvcim_Device_35
8466 0 unpreserved device mosvcim_Device_35
8467 0 unstable device for mosvcm_Device_34
8468 0 unpreserved device mosvcm_Device_34
8469 0 unstable device for mosvci_Device_33
8470 0 unpreserved device mosvci_Device_33
8471 0 unstable device for mosvc_Device_32
8472 0 unpreserved device mosvc_Device_32
8473 0 unstable device for peti_MOS_31
8474 0 unpreserved device peti_MOS_31
8475 0 unstable device for nn_MOS_30
8476 0 unpreserved device nn_MOS_30
8477 0 unstable device for pel_5_Device_29
8478 0 unpreserved device pel_5_Device_29
8479 0 unstable device for pe_5_Device_28
8480 0 unpreserved device pe_5_Device_28
8481 0 unstable device for pel_MOS_27
8482 0 unpreserved device pel_MOS_27
8483 0 unstable device for pe_MOS_26
8484 0 unpreserved device pe_MOS_26
8485 0 unstable device for nel_MOS_25
8486 0 unpreserved device nel_MOS_25
8487 0 unstable device for ne_MOS_24
8488 0 unpreserved device ne_MOS_24
8489 0 unstable device for nisj1_16_Device_23
8490 0 unpreserved device nisj1_16_Device_23
8491 0 unstable device for nhsj1_16c_Device_22
8492 0 unpreserved device nhsj1_16c_Device_22
8493 0 unstable device for nhsj1_10_Device_21
8494 0 unpreserved device nhsj1_10_Device_21
8495 0 unstable device for nhsj1_7_Device_20
8496 0 unpreserved device nhsj1_7_Device_20
8497 0 unstable device for phvu_Device_19
8498 0 unpreserved device phvu_Device_19
8499 0 unstable device for phvtb_Device_18
8500 0 unpreserved device phvtb_Device_18
8501 0 unstable device for phvta_Device_17
8502 0 unpreserved device phvta_Device_17
8503 0 unstable device for ndhvta_Device_16
8504 0 unpreserved device ndhvta_Device_16
8505 0 unstable device for ndhvt_Device_15
8506 0 unpreserved device ndhvt_Device_15
8507 0 unstable device for nhvu_Device_14
8508 0 unpreserved device nhvu_Device_14
8509 0 unstable device for nhvtb_Device_13
8510 0 unpreserved device nhvtb_Device_13
8511 0 unstable device for nhvta_Device_12
8512 0 unpreserved device nhvta_Device_12
8513 0 unstable device for phsj1_16c_Device_11
8514 0 unpreserved device phsj1_16c_Device_11
8515 0 unstable device for phsj1_10_Device_10
8516 0 unpreserved device phsj1_10_Device_10
8517 0 unstable device for phsj1_7_Device_9
8518 0 unpreserved device phsj1_7_Device_9
8519 0 unstable device for pmva_Device_8
8520 0 unpreserved device pmva_Device_8
8521 0 unstable device for nmva_Device_7
8522 0 unpreserved device nmva_Device_7
8523 0 unstable device for pemti_MOS_6
8524 0 unpreserved device pemti_MOS_6
8525 0 unstable device for nnm_MOS_5
8526 0 unpreserved device nnm_MOS_5
8527 0 unstable device for pem_5_Device_4
8528 0 unpreserved device pem_5_Device_4
8529 0 unstable device for pem_MOS_3
8530 0 unpreserved device pem_MOS_3
8531 0 unstable device for ndm_MOS_2
8532 0 unpreserved device ndm_MOS_2
8533 0 unstable device for nem_MOS_1
8534 0 unpreserved device nem_MOS_1
